### ISSUE TITLE
Source file request

### ISSUE THREAD

**Issue by Rux91** [lobotomyp0p/jojo-wiki-network#1]
Hello.
I am a master's student in computer engineering from Italy.
I would like to use the Python source file in this repository to create a project on NetworkX for an university exam. 
However, when I run the code in Google Colab or Jupyter Notebook I get an error on the second to last line of the third cell saying that the dataframe object does not have the 'name' attribute.
Could you kindly tell me how and where to properly run the source file?

![Cattura](https://user-images.githubusercontent.com/44968803/126049595-347eb313-653f-41a6-a926-6bdedcca6eb3.PNG)
![Cattura1](https://user-images.githubusercontent.com/44968803/126049596-4f69f425-df6c-4837-8bb4-c9df620c8dd2.PNG)

**Comment by lobotomyp0p** [comment]
Hello,

I am no longer maintaining this project. I did however give it a try and I got the same error.

When I wrote this project 3 years ago I used Beautiful Soup to parse the source code for the Fandom Wiki website and translate specific elements from the HTML into rows for the pandas dataframe. In the time since then, Fandom Wiki has probably changed the format of the website source code. So what I think this error is saying is that the dataframe has no "name" attribute, probably because the highly specialized code that I wrote 3 years ago doesn't match the form of the website now. So it can't read it.

I recommend that you consult the documentation for Beautiful Soup (https://www.crummy.com/software/BeautifulSoup/bs4/doc/), Pandas (https://pandas.pydata.org/docs/user_guide/index.html#user-guide), and NetworkX. You'll either have to modify the code in the first block of the third cell or construct the dataframe a different way. Good luck with your exam.
